language: java
jdk:
- oraclejdk8
services:
  - mysql
install: .travis-conf/test-script install
before_script: .travis-conf/test-script before_script
script: .travis-conf/test-script test
after_script: .travis-conf/test-script after_script
env:
  - BUILDSTAGE=unittest
  - BUILDSTAGE=systemtest
